export default '<label for="{{id}}">{{this.tittle}}</label>'
+ '		<input'
+ '		type="{{this.type}}"'
+ '	id="{{id}}"'
+ '	name="{{id}}"'
+ '	placeholder="{{this.placeholder}}"'
+ '   value="{{this.value}}"'
+ '	data-required="{{this.required}}"'
+ '		/>'
+ '<p>Это поле обязательно для заполнения</p>';
